name: run-command-azure

on:
  workflow_call:
  workflow_dispatch:
    
jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: write file
        id: write_file
        run: |
          az login --service-principal -u ${{ secrets.azure_client_id }} -p ${{ secrets.azure_secret }} --tenant ${{ secrets.azure_tenant_id }}
          az vm run-command --resource-group "rg-github-actions" -n vm1 --command-id RunShellScript --scripts "'echo hello from GA' > /tmp/ga.txt"